### PR TITLE
anykernel: Fix treble check

### PR DESCRIPTION
**Pull request by msfjarvis**
Android: 1
Nathan: 0

### CODE REVIEW

**Comment by timocapa** [comment]
ty bb

tldr: kernel currently fails to flash on ROMs if they have the flag "ro.treble.enabled" at all, despite being set to "false"

**Comment by ghost** [comment]
#5

**Comment by timocapa** [comment]
that's literally what my first attempt was, until harsh told me that it's bad lmao

after it went downhill because im an idiot  

#3 

i didn't really see what's wrong with it but after i messed up i decided to just let him do it and close my (first ever proper) pr 

e: reeee

**Comment by nathanchance** [comment]
Who the fuck is setting `ro.treble.enabled=false`???

**Comment by timocapa** [comment]
Everyone at this point I think?

**Pull request merged**
